service: spending-api

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-prune-plugin

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs16.x
  stage: $(opt:stage, 'local')

functions:
  graphql:
    handler: ${file(src/controllers/graphql/apollo-handler/graphql.handler)}
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy

      - http:
          path: graphql
          method: get
          cors: true
          integration: lambda-proxy

custom:
  postgres: $(file(./config/${opt:stage, 'dev'}.yml):postgres))
  serverless-offline:
    port: 4000
  bundle:
    linting: false
    excludeFiles: '**.*.test.ts'
    tsConfig: tsconfig.json
    packager: yarn
    ignorePackages:
      - pg-native
    aliases:
      - 'typeorm': './node_modules/typeorm/browser' # see https://github.com/typeorm/typeorm/issues/8714
    